// ข้อมูลสถานที่ท่องเที่ยวยอดนิยมที่กำหนดไว้ล่วงหน้า
export const featuredPlaces = [
  {
    id: "featured-1",
    title: "เกาะพีพี",
    location: "เกาะพีพี",
    province: "กระบี่",
    description:
      "เกาะพีพีเป็นหมู่เกาะที่มีชื่อเสียงระดับโลก มีหาดทรายขาวละเอียด น้ำทะเลใสสีฟ้า และแนวปะการังที่สวยงาม เหมาะสำหรับการดำน้ำตื้นและดำน้ำลึก",
    image_url: "/images/featured/phi-phi-island.jpg",
    placeTypes: ["beach"],
    featured: true,
  },
  {
    id: "featured-2",
    title: "วัดพระแก้ว",
    location: "พระบรมมหาราชวัง",
    province: "กรุงเทพมหานคร",
    description:
      "วัดพระศรีรัตนศาสดาราม หรือวัดพระแก้ว เป็นวัดที่มีความสำคัญในประวัติศาสตร์ไทย เป็นที่ประดิษฐานพระแก้วมรกต และเป็นสถานที่ประกอบพระราชพิธีสำคัญต่างๆ",
    image_url: "/images/featured/wat-phra-kaew.jpg",
    placeTypes: ["temple"],
    featured: true,
  },
  {
    id: "featured-3",
    title: "ดอยอินทนนท์",
    location: "อุทยานแห่งชาติดอยอินทนนท์",
    province: "เชียงใหม่",
    description: "ดอยอินทนนท์เป็นยอดเขาที่สูงที่สุดในประเทศไทย มีอากาศเย็นตลอดทั้งปี มีน้ำตกหลายแห่ง และเป็นแหล่งดูนกที่สำคัญ",
    image_url: "/images/featured/doi-inthanon.jpg",
    placeTypes: ["mountain", "doi"],
    featured: true,
  },
  {
    id: "featured-4",
    title: "อุทยานประวัติศาสตร์สุโขทัย",
    location: "อุทยานประวัติศาสตร์สุโขทัย",
    province: "สุโขทัย",
    description: "อุทยานประวัติศาสตร์สุโขทัยเป็นมรดกโลกทางวัฒนธรรม ประกอบด้วยซากโบราณสถานที่เป็นพระราชวัง วัด และป้อมปราการในอดีต",
    image_url: "/images/featured/sukhothai.jpg",
    placeTypes: ["temple", "museum"],
    featured: true,
  },
  {
    id: "featured-5",
    title: "เกาะสมุย",
    location: "เกาะสมุย",
    province: "สุราษฎร์ธานี",
    description: "เกาะสมุยเป็นเกาะที่ใหญ่เป็นอันดับ 2 ของประเทศไทย มีชายหาดที่สวยงาม รีสอร์ทหรู และแหล่งท่องเที่ยวมากมาย",
    image_url: "/images/featured/koh-samui.jpg",
    placeTypes: ["beach"],
    featured: true,
  },
  {
    id: "featured-6",
    title: "อุทยานแห่งชาติเขาใหญ่",
    location: "อุทยานแห่งชาติเขาใหญ่",
    province: "นครราชสีมา",
    description: "อุทยานแห่งชาติเขาใหญ่เป็นมรดกโลกทางธรรมชาติ มีพื้นที่ป่าดิบชื้นที่อุดมสมบูรณ์ เป็นแหล่งที่อยู่ของสัตว์ป่านานาชนิด",
    image_url: "/images/featured/khao-yai.jpg",
    placeTypes: ["mountain", "park"],
    featured: true,
  },
]
